import React, { PropsWithChildren, Suspense } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { AppProps } from "next/app";
import QueryProvider from "../lib/providers/QueryProvider";
import { ProfileProvider } from "../lib/providers/ProfileProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({ children }: PropsWithChildren<AppProps>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <Suspense fallback={<p> Global loading </p>}>
            <ProfileProvider>{children}</ProfileProvider>
          </Suspense>
        </QueryProvider>
      </body>
    </html>
  );
}
